### ISSUE TITLE
StyleGuide

### ISSUE THREAD

**Issue by crudbug** [cockpit-project/cockpit-design#2]
Cockpit design is well though out. I would love to see an abstracted design language that can used to create other applications. 

For example, 
* http://rizzo.lonelyplanet.com/
* https://www.lightningdesignsystem.com/

**Comment by stefwalter** [comment]
@rhamilto CC

We use Patternfly as our toolkit. I would suggest contributing there in order to influence Cockpit's design language and patterns? http://patternfly.org/

**Comment by crudbug** [comment]
Thanks this looks very promising.

**Comment by stefwalter** [comment]
> How do you create wireframes using Patternfly ? 

We have some assets in the svg files in this repo. See widget-template.svg for some examples.
